spring:
  application:
    name: elib
  datasource:
    driver-class-name: com.mysql.cj.jdbc.Driver
    url: jdbc:mysql://localhost:3306/lib_manage?serverTimezone=GMT%2B8&autoReconnect=true&allowMultiQueries=true&useUnicode=true&characterEncoding=utf8&zeroDateTimeBehavior=convertToNull&useSSL=false
    username: leo
    password: lou..200499
    type: com.alibaba.druid.pool.DruidDataSource
  data:
    redis:
      host: localhost
      port: 6379
      password: #没有密码的话不用填
      timeout: 10000
      database: 0
  mail:
    host: smtp.163.com
    username: lskleo@163.com
    password: ZNFXUXHKVKCSZPWX
    default-encoding: UTF-8
#  elasticsearch:
#    uris: https://8.148.24.68:9200
#    username: elastic
#    password: N3HJYi89CVkShkiBaGKt
#logging:
#  level:
#    org:
#      springframework:
#        data:
#          elasticsearch:
#            core:
#              query: debug

server:
  port: 9021
  
# 设置mybatis寻找对应.xml文件的位置
mybatis:
  type-aliases-package: com.leo.elib.entity, com.leo.elib.entity.dto.dao, com.leo.elib.mapper.type
  mapper-locations: classpath:mapper/*.xml
  type-handlers-package: com.leo.elib.mapper.type
#  configuration:
#    log-impl: org.apache.ibatis.logging.stdout.StdOutImpl

#es:
#  host: es-cn-y1i3zlquw000635jb.public.elasticsearch.aliyuncs.com
#  port: 9200
#  https:
#    enabled: false
#    insecure: true
#  username: elastic
#  password: Lou200499
#  doc:
#    book_detail_info:
#      index_name: book_detailed_info
es:
  host: 127.0.0.1 # 111.230.63.174
  port: 9200
  https:
    enabled: false
    insecure: true
  username: elastic
  password: M5_nODOEc=Xmb30kJRTS
  doc:
    book_detail_info:
      index_name: book_detailed_info
    author_info:
      index_name: author
    publisher_info:
      index_name: publisher
    viewing_history:
      book:
        index_name: book_viewing_history

async:
  thread-pool:
    core-pool-size: 2
    max-pool-size: 10
    queue-capacity: 25
    keep-alive-seconds: 60
    thread-name-prefix: async-service-
    await-termination-seconds: 30

#container:
#  redis:
#    at_hash: elib:hash:at
#    rt_hash: elib:hash:rt
#    book_category_hash: elib:hash:book_cate
#    book_tag_hash_name: elib:hash:book_tag:name
#    book_tag_hash_whole: elib:hash:book_tag:whole
#
#    content_hash: elib:hash:content
container:
  redis:
    token:
      at-hash: elib:hash:at
      rt-hash: elib:hash:rt
    book-cache:
      book-cate-hash: elib:hash:book_cate
      book-tag-hash-name: elib:hash:book_tag:name
      book-tag-hash-whole: elib:hash:book_tag:whole
    template:
      content-hash: elib:hash:content
    authen-code:
      authen-code-hash: elib:hash:authen_code
      authen-code-zset: elib:zset:authen_code
      clean-interval-ms: 3600000 # 1 hour
    chart:
      trending_book_zset: elib:zset:trending_book
#      high_rating_book_zset: elib:zset:high_rating_book
      trending_author_zset: elib:zset:trending_author
    chart_cache:
      book:
        cont-name: elib:hash:popular_book
        max_capacity: 3000
      author:
        cont-name: elib:hash:popular_author
        max_capacity: 1000
    announcement:
      cont-name: elib:list:announcement
      max_capacity: 1000

authen:
  verify:
    length: 6
  captcha:
    length: 4
  setting:
    expiration: 300

jwt:
  at_secret: secretForElibAT
  rt_secret: secretForElibRT
  at_expiration: 3600
  rt_expiration: 43200

path:
  filterExcludes: 
    - /auth
    - /api/book_info

sys_setting:
  bookshelf:
    constraint: 50 # 个人书架只能最多上传50本书, beware此值最大不能超过short的最大值
  #书籍收藏
  book_mark:
    constraint: 1000 # 星星收藏最多1000本书

  reservation:
    reserve_and_unreturn_limit: 10 #已经预约以及未归还的书籍之和不能超过10本，超过则不能再预约
    max_overdue_per_month: 3 #每月最多超期3次
    max_try_times: 3 #最多尝试预约3次

  viewing_history:
    book:
     max_days: 30 #最多保存30天的浏览记录

  user_behavior:
    weight:
      tap: 1
      collect: 3
      reserve: 6

  chart:
    trending_book:
      list_size: 200 #榜单最多200本书
      popularity_decay_rate: 0.95 #每天衰减5%
    high_rating_book:
      list_size: 200
    trending_author:
      list_size: 100

  announcement:
    update-when-reboot: true #服务器重启时缓存从数据库更新