spring:
  application:
    name: elib
  datasource:
    driver-class-name: com.mysql.cj.jdbc.Driver
    url: jdbc:mysql://localhost:3306/lib_manage?serverTimezone=GMT%2B8&autoReconnect=true&allowMultiQueries=true&useUnicode=true&characterEncoding=utf8&zeroDateTimeBehavior=convertToNull&useSSL=false
    username: leo
    password: lou..200499
    type: com.alibaba.druid.pool.DruidDataSource
  data:
    redis:
      host: localhost
      port: 6379
      password: #没有密码的话不用填
      timeout: 10000
      database: 0

server:
  port: 9021

container:
  redis:
    at_hash: elib:hash:at
    rt_hash: elib:hash:rt
    book_category_hash: elib:hash:book_cate
    book_tag_hash_name: elib:hash:book_tag:name
    book_tag_hash_whole: elib:hash:book_tag:whole
  
# 设置mybatis寻找对应.xml文件的位置
mybatis:
  type-aliases-package: com.leo.elib.entity.dto.dao
  mapper-locations: classpath:mapper/*.xml
#  configuration:
#    log-impl: org.apache.ibatis.logging.stdout.StdOutImpl

jwt:
  at_secret: secretForElibAT
  rt_secret: secretForElibRT
  at_expiration: 3600
  rt_expiration: 43200

path:
  filterExcludes: 
    - /auth
    - /api/book_info